version: '3.4'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "recipeDB99!"
        ports:
            - "1433:1433"

    api:
        build: .
        ports:
            - "80:80"
            #- "433:433"